version: '3'
services:
  user:
    build:
      context: ./
      dockerfile: deploy/user/Dockerfile
  mailer:
    build:
      context: ./
      dockerfile: deploy/mailer/Dockerfile
  category:
    build:
      context: ./
      dockerfile: deploy/category/Dockerfile
  projects:
    build:
      context: ./
      dockerfile: deploy/projects/Dockerfile
  gateway:
    build:
      context: ./
      dockerfile: deploy/gateway/Dockerfile
    ports:
      - "3890:3890"

networks:
  default:
    external:
      name: relay
